import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import AuthProvider from "@/context/AuthProvider";
import "./globals.css";
import Chatbot from "@/components/chatbot/chatbot";
import { Toaster } from "@/components/ui/sonner"
// import GoogleMapsLoader from "@/components/GoogleMapsLoader";

const geistSans = GeistSans;
const geistMono = GeistMono;


export const metadata: Metadata = {
  title: "EcoFarm Assist",
  description: "Generated by Sudhanshu",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY);
  return (
    <html lang="en">
      <head>
        <script
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
          async
          defer
        ></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          {/* <GoogleMapsLoader /> */}
          {children}
          <Chatbot />
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
